# Generated by Django 6.0.3 on 2026-06-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='api_key_groq',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chave API Groq'),
        ),
    ]
