# Generated by Django 6.0.3 on 2026-04-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoBTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=32, unique=True)),
                ('ativo', models.CharField(max_length=20)),
                ('movimentacao', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=50)),
                ('valor_total', models.DecimalField(decimal_places=8, max_digits=20)),
                ('valor_liquido', models.DecimalField(decimal_places=8, max_digits=20)),
                ('satoshis', models.DecimalField(decimal_places=8, max_digits=20)),
                ('taxa_porcentual', models.DecimalField(decimal_places=4, max_digits=10)),
                ('taxa_ativo', models.CharField(max_length=20)),
                ('taxa_quantidade', models.DecimalField(decimal_places=8, max_digits=20)),
                ('cotacao_do_dia', models.DecimalField(decimal_places=2, max_digits=20)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('data', models.DateTimeField()),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
